name: Build and Push PostgreSQL Image

on:
  workflow_dispatch:

jobs:
  build-postgres:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Get latest PostgreSQL version
        id: get_version
        run: |
          MINOR_VERSION=$(./get-postgres-version.sh 17)
          echo "minor_version=${MINOR_VERSION}" >> $GITHUB_OUTPUT

      - name: Log in to registry
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login "${{ secrets.REGISTRY_URL }}" -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

      - name: Build and push
        run: |
          IMAGE="${{ secrets.REGISTRY_URL }}/postgres-ssl"
          FULL=${{ steps.get_version.outputs.minor_version }}

          docker build \
            -f Dockerfile.17 \
            --build-arg POSTGRES_VERSION=${FULL} \
            -t "${IMAGE}:17" \
            -t "${IMAGE}:${FULL}" \
            -t "${IMAGE}:latest" \
            .

          docker push "${IMAGE}" --all-tags
