name: Build and Push PostgreSQL Image

on:
  workflow_dispatch:

jobs:
  build-postgres:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Get latest PostgreSQL version
        id: get_version
        run: |
          MINOR_VERSION=$(./get-postgres-version.sh 17)
          echo "minor_version=${MINOR_VERSION}" >> $GITHUB_OUTPUT

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.17
          push: true
          build-args: POSTGRES_VERSION=${{ steps.get_version.outputs.minor_version }}
          tags: |
            ${{ secrets.REGISTRY_URL }}/general/postgres-ssl:17
            ${{ secrets.REGISTRY_URL }}/general/postgres-ssl:${{ steps.get_version.outputs.minor_version }}
            ${{ secrets.REGISTRY_URL }}/general/postgres-ssl:latest
